### ISSUE TITLE
Fix arcade hopping issue

### ISSUE THREAD

**Issue by korisya** [korisya/kensaku#10]
When one player who is last to play at one location moves to another, the two players before the moving player at the former location will have appeared to log in. For example, if Milpitas looks like
```
RCKYWONG 51448180
MEGUMIN 51400807
T3ALIZES 51415530
```
and `RCKYWONG` logs in to San Jose, then `RCKYWONG` will be removed from Milpitas:
```
MEGUMIN 51400807
T3ALIZES 51415530
```

The bot will think that `MEGUMIN` and `T3ALIZES` have logged in, even though they haven't.

To fix this, we would have to retrieve data from every cab first, and then check whether the two players stored in every cab's `newPlayers` exist in any other cab's `players`.

**Comment by ricky-wong** [comment]
Something's broken, and honestly I should've thought-about and commented on this issue earlier. This is also a unique case that we actually don't see happen often in the real world, so there's minimal urgency.

If the bot compares before and after, you can notice that someone dropped out, rather than other people getting bumped up. I'd prefer something that does a comparison along these lines.

**Comment by ricky-wong** [comment]
This might be working, but the solution might be less than ideal, I'll open another issue if I get around to figuring it out.
